2013-12-05T13:49:12.026929+00:00 app[web.1]: running with user andygee@gmail.com 
2013-12-05T13:49:19.995084+00:00 app[web.1]: FOUND 3 PARTIES
2013-12-05T13:49:20.117396+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2013-12-05T13:49:20.128364+00:00 app[web.1]: AVAILABLE PARTIES 10 
2013-12-05T14:53:16.746290+00:00 app[web.1]: 2013-12-05 14:53:16 [7] [INFO] Worker exiting (pid: 7)
2013-12-05T14:53:16.748007+00:00 app[web.1]: 2013-12-05 14:53:16 [2] [INFO] Handling signal: term
2013-12-05T14:53:16.771656+00:00 app[web.1]: 2013-12-05 14:53:16 [2] [INFO] Shutting down: Master
2013-12-06T00:29:15.195067+00:00 app[web.1]: 2013-12-06 00:29:15 [2] [INFO] Starting gunicorn 18.0
2013-12-06T00:29:15.195661+00:00 app[web.1]: 2013-12-06 00:29:15 [2] [INFO] Listening at: http://0.0.0.0:4228 (2)
2013-12-06T00:29:15.195736+00:00 app[web.1]: 2013-12-06 00:29:15 [2] [INFO] Using worker: sync
2013-12-06T00:29:15.212046+00:00 app[web.1]: 2013-12-06 00:29:15 [7] [INFO] Booting worker with pid: 7
2013-12-06T00:31:18.822002+00:00 app[web.1]: running with user legendairy647@gmail.com 
2013-12-06T00:32:21.404488+00:00 app[web.1]: cannot find gdoc name
2013-12-06T00:32:21.404698+00:00 app[web.1]: show entries
2013-12-06T00:32:21.406068+00:00 app[web.1]: Traceback (most recent call last):
2013-12-06T00:32:21.406068+00:00 app[web.1]: 2013-12-06 00:32:21 [7] [ERROR] Error handling request
2013-12-06T00:32:21.406068+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2013-12-06T00:32:21.406068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2013-12-06T00:32:21.406068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2013-12-06T00:32:21.406364+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2013-12-06T00:32:21.406364+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2013-12-06T00:32:21.406364+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2013-12-06T00:32:21.406364+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2013-12-06T00:32:21.406364+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-06T00:32:21.406364+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2013-12-06T00:32:21.406364+00:00 app[web.1]:     response = self.full_dispatch_request()
2013-12-06T00:32:21.406364+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2013-12-06T00:32:21.406364+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2013-12-06T00:32:21.406364+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2013-12-06T00:32:21.406551+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-06T00:32:21.406551+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2013-12-06T00:32:21.406551+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2013-12-06T00:32:21.406551+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2013-12-06T00:32:21.406551+00:00 app[web.1]:     rv = self.dispatch_request()
2013-12-06T00:32:21.406551+00:00 app[web.1]:   File "/app/rosterrun.py", line 108, in show_entries
2013-12-06T00:32:21.406551+00:00 app[web.1]:     if session['g_spreadsheet_id'] is not None and session['g_worksheet_id'] is not None:
2013-12-06T00:32:21.406551+00:00 app[web.1]:     __getitem__ = lambda x, i: x._get_current_object()[i]
2013-12-06T00:32:21.406551+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/local.py", line 368, in <lambda>
2013-12-06T00:32:21.406551+00:00 app[web.1]: KeyError: 'g_spreadsheet_id'
2013-12-06T00:33:48.580121+00:00 app[web.1]: cannot find gdoc name
2013-12-06T00:33:48.580682+00:00 app[web.1]: show entries
2013-12-06T00:33:48.581605+00:00 app[web.1]: Traceback (most recent call last):
2013-12-06T00:33:48.581605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2013-12-06T00:33:48.581605+00:00 app[web.1]: 2013-12-06 00:33:48 [7] [ERROR] Error handling request
2013-12-06T00:33:48.581605+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2013-12-06T00:33:48.581605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2013-12-06T00:33:48.581605+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2013-12-06T00:33:48.581605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2013-12-06T00:33:48.581605+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2013-12-06T00:33:48.581605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2013-12-06T00:33:48.581605+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-06T00:33:48.581763+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2013-12-06T00:33:48.581763+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2013-12-06T00:33:48.581763+00:00 app[web.1]:     response = self.full_dispatch_request()
2013-12-06T00:33:48.581763+00:00
 app[web.1]:     rv = self.handle_user_exception(e)
2013-12-06T00:33:48.581763+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2013-12-06T00:33:48.581763+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-06T00:33:48.581763+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2013-12-06T00:33:48.581763+00:00 app[web.1]:     rv = self.dispatch_request()
2013-12-06T00:33:48.581763+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2013-12-06T00:33:48.581935+00:00 app[web.1]:   File "/app/rosterrun.py", line 108, in show_entries
2013-12-06T00:33:48.581935+00:00 app[web.1]:     if session['g_spreadsheet_id'] is not None and session['g_worksheet_id'] is not None:
2013-12-06T00:33:48.581935+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/local.py", line 368, in <lambda>
2013-12-06T00:33:48.581935+00:00 app[web.1]:     __getitem__ = lambda x, i: x._get_current_object()[i]
2013-12-06T00:33:48.581763+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2013-12-06T00:33:48.581935+00:00 app[web.1]: KeyError: 'g_spreadsheet_id'
2013-12-06T02:09:19.043589+00:00 app[web.1]: 2013-12-06 02:09:19 [2] [INFO] Handling signal: term
2013-12-06T02:09:19.038535+00:00 app[web.1]: 2013-12-06 02:09:19 [7] [INFO] Worker exiting (pid: 7)
2013-12-06T02:09:19.072288+00:00 app[web.1]: 2013-12-06 02:09:19 [2] [INFO] Shutting down: Master
