2013-12-05T02:54:39.042458+00:00 heroku[web.1]: State changed from starting to up
2013-12-05T02:54:40.871699+00:00 heroku[api]: Starting process with command `python` by andygee@gmail.com
2013-12-05T02:54:55.909863+00:00 heroku[run.1472]: Awaiting client
2013-12-05T02:54:55.963319+00:00 heroku[run.1472]: Starting process with command `python`
2013-12-05T02:55:13.193904+00:00 heroku[run.1472]: Process exited with status 0
2013-12-05T02:55:13.203929+00:00 heroku[run.1472]: State changed from up to complete
2013-12-05T02:55:17.224773+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T02:55:17.261527+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="108.0.233.129" dyno=web.1 connect=2ms service=59ms status=302 bytes=219
2013-12-05T02:55:27.031903+00:00 heroku[router]: at=info method=GET path=/auth_return?code=4/hW_8hP1CqUGQWpxsK0-3SPVMACBU.gnecwuM9eh8eMqTmHjyTFGP2d2CBhQI host=rosterrun.herokuapp.com fwd="108.0.233.129" dyno=web.1 connect=9ms service=2150ms status=302 bytes=209
2013-12-05T02:55:27.226798+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T02:55:27.327952+00:00 app[web.1]: found credentials
2013-12-05T02:55:27.365271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2013-12-05T02:55:27.365271+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2013-12-05T02:55:27.365271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2013-12-05T02:55:27.365271+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2013-12-05T02:55:27.365271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2013-12-05T02:55:27.365271+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-05T02:55:27.365466+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2013-12-05T02:55:27.365466+00:00 app[web.1]:     response = self.full_dispatch_request()
2013-12-05T02:55:27.365466+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2013-12-05T02:55:27.365271+00:00 app[web.1]: 2013-12-05 02:55:27 [7] [ERROR] Error handling request
2013-12-05T02:55:27.365271+00:00 app[web.1]: Traceback (most recent call last):
2013-12-05T02:55:27.368908+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="108.0.233.129" dyno=web.1 connect=1ms service=157ms status=500 bytes=135
2013-12-05T02:55:27.365466+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2013-12-05T02:55:27.365466+00:00 app[web.1]:     rv = self.dispatch_request()
2013-12-05T02:55:27.365466+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2013-12-05T02:55:27.365466+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2013-12-05T02:55:27.365648+00:00 app[web.1]:   File "/app/rosterrun.py", line 109, in show_entries
2013-12-05T02:55:27.365466+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2013-12-05T02:55:27.365648+00:00 app[web.1]:   File "/app/scheduler.py", line 159, in testConnectToSpreadsheetsServiceOAuth
2013-12-05T02:55:27.365648+00:00 app[web.1]:     feed = gd_client.GetSpreadsheets(query=q)
2013-12-05T02:55:27.365271+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2013-12-05T02:55:27.365271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2013-12-05T02:55:27.365648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/client.py", line 640, in get_feed
2013-12-05T02:55:27.365648+00:00 app[web.1]:     **kwargs)
2013-12-05T02:55:27.365648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/client.py", line 267, in request
2013-12-05T02:55:27.365648+00:00 app[web.1]:     uri=uri, auth_token=auth_token, http_request=http_request, **kwargs)
2013-12-05T02:55:27.365648+00:00 app[web.1]:     (g_s_id, g_w_id) = testConnectToSpreadsheetsServiceOAuth(credentials, session['doc'])
2013-12-05T02:55:27.366069+00:00 app[web.1]:     http_request.uri.query[name] = str(value)
2013-12-05T02:55:27.366069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/service.py", line 1718, in __str__
2013-12-05T02:55:27.365648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/spreadsheets/client.py", line 78, in get_spreadsheets
2013-12-05T02:55:27.365466+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-05T02:55:27.365466+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2013-12-05T02:55:27.366069+00:00 app[web.1]:     return self.ToUri()
2013-12-05T02:55:27.366069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/service.py", line 1715, in ToUri
2013-12-05T02:55:27.366069+00:00 app[web.1]:     return atom.service.BuildUri(q_feed, self)
2013-12-05T02:55:27.366069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/atom/service.py", line 584, in BuildUri
2013-12-05T02:55:27.366069+00:00 app[web.1]:     for param, value in (url_parameters or {}).items()]
2013-12-05T02:55:27.366069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/atom/client.py", line 101, in request
2013-12-05T02:55:27.365648+00:00 app[web.1]:     desired_class=desired_class, **kwargs)
2013-12-05T02:55:27.366260+00:00 app[web.1]:     if ' ' in s:
2013-12-05T02:55:27.366260+00:00 app[web.1]: TypeError: argument of type 'NoneType' is not iterable
2013-12-05T02:55:27.366260+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib.py", line 1286, in quote_plus
2013-12-05T02:55:27.366069+00:00 app[web.1]:     parameter_list = DictionaryToParamList(url_params, escape_params)
2013-12-05T02:55:27.366069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/atom/service.py", line 551, in DictionaryToParamList
2013-12-05T02:55:31.716708+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="108.0.233.129" dyno=web.1 connect=7ms service=637ms status=500 bytes=135
2013-12-05T02:55:31.711015+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T02:55:31.713167+00:00 app[web.1]: found credentials
2013-12-05T02:55:31.714234+00:00 app[web.1]: 2013-12-05 02:55:31 [7] [ERROR] Error handling request
2013-12-05T02:55:31.714234+00:00 app[web.1]: Traceback (most recent call last):
2013-12-05T02:55:31.714234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2013-12-05T02:55:31.714234+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2013-12-05T02:55:31.714234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2013-12-05T02:55:31.714234+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2013-12-05T02:55:31.714234+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-05T02:55:31.714481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2013-12-05T02:55:31.714234+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2013-12-05T02:55:31.714234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2013-12-05T02:55:31.714481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2013-12-05T02:55:31.714481+00:00 app[web.1]:     response = self.full_dispatch_request()
2013-12-05T02:55:31.714481+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2013-12-05T02:55:31.714234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2013-12-05T02:55:31.714481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2013-12-05T02:55:31.714481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2013-12-05T02:55:31.714481+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2013-12-05T02:55:31.714481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2013-12-05T02:55:31.714689+00:00 app[web.1]:   File "/app/rosterrun.py", line 109, in show_entries
2013-12-05T02:55:31.714481+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-05T02:55:31.714689+00:00 app[web.1]:     (g_s_id, g_w_id) = testConnectToSpreadsheetsServiceOAuth(credentials, session['doc'])
2013-12-05T02:55:31.714689+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/spreadsheets/client.py", line 78, in get_spreadsheets
2013-12-05T02:55:31.714689+00:00 app[web.1]:   File "/app/scheduler.py", line 159, in testConnectToSpreadsheetsServiceOAuth
2013-12-05T02:55:31.714481+00:00 app[web.1]:     rv = self.dispatch_request()
2013-12-05T02:55:31.714689+00:00 app[web.1]:     feed = gd_client.GetSpreadsheets(query=q)
2013-12-05T02:55:31.714689+00:00 app[web.1]:     desired_class=desired_class, **kwargs)
2013-12-05T02:55:31.714689+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/client.py", line 640, in get_feed
2013-12-05T02:55:31.715243+00:00 app[web.1]:     return self.ToUri()
2013-12-05T02:55:31.714689+00:00 app[web.1]:     uri=uri, auth_token=auth_token, http_request=http_request, **kwargs)
2013-12-05T02:55:31.715243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/atom/client.py", line 101, in request
2013-12-05T02:55:31.714689+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/client.py", line 267, in request
2013-12-05T02:55:31.715243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/service.py", line 1718, in __str__
2013-12-05T02:55:31.715243+00:00 app[web.1]:     http_request.uri.query[name] = str(value)
2013-12-05T02:55:31.714689+00:00 app[web.1]:     **kwargs)
2013-12-05T02:55:31.715243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gdata/service.py", line 1715, in ToUri
2013-12-05T02:55:31.715243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/atom/service.py", line 584, in BuildUri
2013-12-05T02:55:31.715243+00:00 app[web.1]:     return atom.service.BuildUri(q_feed, self)
2013-12-05T02:55:31.715539+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib.py", line 1286, in quote_plus
2013-12-05T02:55:31.715243+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/atom/service.py", line 551, in DictionaryToParamList
2013-12-05T02:55:31.715243+00:00 app[web.1]:     for param, value in (url_parameters or {}).items()]
2013-12-05T02:55:31.715243+00:00 app[web.1]:     parameter_list = DictionaryToParamList(url_params, escape_params)
2013-12-05T02:55:31.715539+00:00 app[web.1]:     if ' ' in s:
2013-12-05T02:55:31.715539+00:00 app[web.1]: TypeError: argument of type 'NoneType' is not iterable
