2013-12-05T11:03:07.089994+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2013-12-05T11:03:07.089793+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-05T11:03:07.089994+00:00 app[web.1]:     response = self.full_dispatch_request()
2013-12-05T11:03:07.090170+00:00 app[web.1]:     run_calculation()
2013-12-05T11:03:07.090170+00:00 app[web.1]:     badDualClientPlayers = [(c[0], [r.Name for r in c[1]]) for c in mergedClientPlayerAssignment if c[1][1] not in c[1][0].CanDualClientRole]
2013-12-05T11:03:07.090170+00:00 app[web.1]:     parties = run_scheduler_OAuth(credentials, session['doc'])
2013-12-05T11:03:07.090170+00:00 app[web.1]:   File "/app/rosterrun.py", line 156, in run_calculation
2013-12-05T11:03:07.090170+00:00 app[web.1]:     parties += combineByRoleAssignment(avChar, instance, quests, viablePartyIndex)
2013-12-05T11:03:07.090170+00:00 app[web.1]:   File "/app/rosterrun.py", line 98, in show_entries
2013-12-05T11:03:07.089994+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2013-12-05T11:03:07.090170+00:00 app[web.1]:   File "/app/scheduler.py", line 291, in combineByRoleAssignment
2013-12-05T11:03:07.090170+00:00 app[web.1]:   File "/app/scheduler.py", line 117, in run_scheduler_OAuth
2013-12-05T11:03:07.090170+00:00 app[web.1]: IndexError: list index out of range
2013-12-05T11:03:10.369877+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T11:03:10.369877+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2013-12-05T11:03:10.376214+00:00 app[web.1]: AVAILABLE PARTIES 0 
2013-12-05T11:31:23.588086+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T11:31:23.588264+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2013-12-05T11:31:23.594783+00:00 app[web.1]: AVAILABLE PARTIES 0 
2013-12-05T11:32:49.892465+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T11:32:49.900126+00:00 app[web.1]: AVAILABLE PARTIES 0 
2013-12-05T11:32:49.892465+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2013-12-05T11:32:54.519127+00:00 app[web.1]: running with user andygee@gmail.com 
2013-12-05T11:32:57.137201+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T11:32:57.137201+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2013-12-05T11:32:57.143992+00:00 app[web.1]: AVAILABLE PARTIES 0 
2013-12-05T11:33:01.738863+00:00 app[web.1]: running with user andygee@gmail.com 
2013-12-05T11:33:02.430306+00:00 app[web.1]: trying to run parties
2013-12-05T11:33:32.390863+00:00 app[web.1]: 2013-12-05 11:33:32 [2] [CRITICAL] WORKER TIMEOUT (pid:7)
2013-12-05T11:33:32.407837+00:00 app[web.1]: 2013-12-05 11:33:32 [2] [CRITICAL] WORKER TIMEOUT (pid:7)
2013-12-05T11:33:32.415766+00:00 app[web.1]: 2013-12-05 11:33:32 [12] [INFO] Booting worker with pid: 12
2013-12-05T11:40:50.120256+00:00 app[web.1]: running with user andygee@gmail.com 
2013-12-05T11:40:57.084290+00:00 app[web.1]: running with user andygee@gmail.com 
2013-12-05T11:41:01.040842+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2013-12-05T11:41:01.040842+00:00 app[web.1]: ImmutableMultiDict([])
2013-12-05T11:41:01.047787+00:00 app[web.1]: AVAILABLE PARTIES 0 
2013-12-05T11:41:06.627089+00:00 app[web.1]: running with user andygee@gmail.com 
2013-12-05T11:41:07.593201+00:00 app[web.1]: trying to run parties
2013-12-05T11:41:11.616446+00:00 app[web.1]: NUMBER OF VALID COMBINATIONS 0
2013-12-05T11:41:12.141518+00:00 app[web.1]: NUMBER OF VALID COMBINATIONS 3
2013-12-05T11:41:12.141518+00:00 app[web.1]: FOUND PARTIES [[<scheduler.Combination instance at 0x2b93908>, <scheduler.Combination instance at 0x2b93098>, <scheduler.Combination instance at 0x2b93368>, <scheduler.Combination instance at 0x2b930e0>, <scheduler.Combination instance at 0x2b93440>], [<scheduler.Combination instance at 0x2b95ab8>, <scheduler.Combination instance at 0x2b93f80>, <scheduler.Combination instance at 0x2b93c68>, <scheduler.Combination instance at 0x2b93878>, <scheduler.Combination instance at 0x2b93b00>], [<scheduler.Combination instance at 0x2b93d88>, <scheduler.Combination instance at 0x2b93a28>, <scheduler.Combination instance at 0x2b93830>, <scheduler.Combination instance at 0x2b939e0>, <scheduler.Combination instance at 0x2b93950>]]
2013-12-05T11:44:41.615277+00:00 app[web.1]: running with user andygee@gmail.com 
2013-12-05T11:44:42.341365+00:00 app[web.1]: trying to run parties
2013-12-05T11:45:04.296881+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2013-12-05T11:45:04.296881+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2013-12-05T11:45:04.296881+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2013-12-05T11:45:04.296881+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2013-12-05T11:45:04.296881+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2013-12-05T11:45:04.296881+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2013-12-05T11:45:04.296881+00:00 app[web.1]: 2013-12-05 11:45:04 [12] [ERROR] Error handling request
2013-12-05T11:45:04.296881+00:00 app[web.1]: Traceback (most recent call last):
2013-12-05T11:45:04.297111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2013-12-05T11:45:04.297111+00:00 app[web.1]:     response = self.full_dispatch_request()
2013-12-05T11:45:04.297111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2013-12-05T11:45:04.297111+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2013-12-05T11:45:04.296881+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-05T11:45:04.296881+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2013-12-05T11:45:04.297111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2013-12-05T11:45:04.297111+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-12-05T11:45:04.297111+00:00 app[web.1]:     rv = self.dispatch_request()
2013-12-05T11:45:04.297111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2013-12-05T11:45:04.297111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2013-12-05T11:45:04.297289+00:00 app[web.1]:     parties = run_scheduler_OAuth(credentials, session['doc'])
2013-12-05T11:45:04.297289+00:00 app[web.1]:     parties += combineByRoleAssignment(avChar, instance, quests, viablePartyIndex)
2013-12-05T11:45:04.297289+00:00 app[web.1]:     badDualClientPlayers = [(c[0], [r.Name for r in c[1]]) for c in mergedClientPlayerAssignment if c[1][1] not in c[1][0].CanDualClientRole]
2013-12-05T11:45:04.297111+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2013-12-05T11:45:04.297289+00:00 app[web.1]:   File "/app/rosterrun.py", line 98, in show_entries
2013-12-05T11:45:04.297289+00:00 app[web.1]: IndexError: list index out of range
2013-12-05T11:45:04.297289+00:00 app[web.1]:   File "/app/scheduler.py", line 291, in combineByRoleAssignment
2013-12-05T11:45:04.297289+00:00 app[web.1]:     run_calculation()
2013-12-05T11:45:04.297289+00:00 app[web.1]:   File "/app/scheduler.py", line 117, in run_scheduler_OAuth
2013-12-05T11:45:04.297289+00:00 app[web.1]:   File "/app/rosterrun.py", line 156, in run_calculation
