2014-02-10T07:00:02.585150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2014-02-10T07:00:02.585150+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:00:02.584922+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2014-02-10T07:00:02.585150+00:00 app[web.1]:     response = self.full_dispatch_request()
2014-02-10T07:00:02.584922+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2014-02-10T07:00:02.585150+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2014-02-10T07:00:02.585150+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2014-02-10T07:00:02.585150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2014-02-10T07:00:02.585150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2014-02-10T07:00:02.585150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2014-02-10T07:00:02.585334+00:00 app[web.1]:     return render_template('show_entries.html', combinations=availableParties, characters=chars)
2014-02-10T07:00:02.585334+00:00 app[web.1]: UnboundLocalError: local variable 'chars' referenced before assignment
2014-02-10T07:00:02.585150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2014-02-10T07:00:02.585150+00:00 app[web.1]:     rv = self.dispatch_request()
2014-02-10T07:00:02.585334+00:00 app[web.1]:   File "/app/rosterrun.py", line 308, in show_entries
2014-02-10T07:00:02.604530+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com request_id=317b4a7c-012c-41b7-82b5-8c2322235f7a fwd="67.105.106.9" dyno=web.1 connect=1ms service=552ms status=500 bytes=135
2014-02-10T07:03:09+00:00 heroku[slug-compiler]: Slug compilation started
2014-02-10T07:04:36.060510+00:00 heroku[api]: Deploy ede1b03 by andygee@gmail.com
2014-02-10T07:04:36.078154+00:00 heroku[api]: Release v181 created by andygee@gmail.com
2014-02-10T07:04:36+00:00 heroku[slug-compiler]: Slug compilation finished
2014-02-10T07:04:36.531351+00:00 heroku[web.1]: State changed from up to starting
2014-02-10T07:04:36.582731+00:00 heroku[worker.1]: State changed from up to starting
2014-02-10T07:04:36.610058+00:00 heroku[worker.2]: State changed from up to starting
2014-02-10T07:04:40.025570+00:00 heroku[worker.2]: Stopping all processes with SIGTERM
2014-02-10T07:04:40.250043+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2014-02-10T07:04:40.822096+00:00 app[worker.2]: 07:04:40 Warm shut down requested.
2014-02-10T07:04:41.056874+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2014-02-10T07:04:41.819716+00:00 app[worker.1]: 07:04:41 Warm shut down requested.
2014-02-10T07:04:41.012870+00:00 app[web.1]: 2014-02-10 07:04:41 [7] [INFO] Worker exiting (pid: 7)
2014-02-10T07:04:41.605163+00:00 app[web.1]: 2014-02-10 07:04:41 [2] [INFO] Handling signal: term
2014-02-10T07:04:41.655790+00:00 app[web.1]: 2014-02-10 07:04:41 [2] [INFO] Shutting down: Master
2014-02-10T07:04:42.280598+00:00 heroku[worker.2]: Process exited with status 0
2014-02-10T07:04:43.294858+00:00 heroku[worker.1]: Process exited with status 0
2014-02-10T07:04:43.300259+00:00 heroku[web.1]: Process exited with status 0
2014-02-10T07:04:46.306206+00:00 heroku[worker.2]: Starting process with command `python worker.py`
2014-02-10T07:04:47.037148+00:00 heroku[worker.2]: State changed from starting to up
2014-02-10T07:04:47.493200+00:00 app[worker.2]: 07:04:47 RQ worker started, version 0.3.13
2014-02-10T07:04:47.495296+00:00 app[worker.2]: 07:04:47 
2014-02-10T07:04:47.495462+00:00 app[worker.2]: 07:04:47 *** Listening on high, default, low...
2014-02-10T07:04:48.052650+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-02-10T07:04:48.640029+00:00 heroku[worker.1]: State changed from starting to up
2014-02-10T07:04:49.301438+00:00 app[worker.1]: 07:04:49 RQ worker started, version 0.3.13
2014-02-10T07:04:49.303467+00:00 app[worker.1]: 07:04:49 
2014-02-10T07:04:49.303595+00:00 app[worker.1]: 07:04:49 *** Listening on high, default, low...
2014-02-10T07:04:52.442559+00:00 heroku[web.1]: Starting process with command `gunicorn rosterrun:app`
2014-02-10T07:04:54.825150+00:00 app[web.1]: 2014-02-10 07:04:54 [2] [INFO] Starting gunicorn 18.0
2014-02-10T07:04:54.828567+00:00 app[web.1]: 2014-02-10 07:04:54 [2] [INFO] Listening at: http://0.0.0.0:38306 (2)
2014-02-10T07:04:54.832955+00:00 app[web.1]: 2014-02-10 07:04:54 [2] [INFO] Using worker: sync
2014-02-10T07:04:54.856362+00:00 app[web.1]: 2014-02-10 07:04:54 [7] [INFO] Booting worker with pid: 7
2014-02-10T07:04:55.253429+00:00 heroku[web.1]: State changed from starting to up
2014-02-10T07:04:57.274499+00:00 app[web.1]: show entries
2014-02-10T07:04:57.274605+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-02-10T07:04:57.274162+00:00 app[web.1]: No job in session
2014-02-10T07:04:57.274499+00:00 app[web.1]: cannot find gdoc name
2014-02-10T07:04:57.429601+00:00 app[web.1]: issue finding the available parties
2014-02-10T07:04:57.483414+00:00 app[web.1]: 2014-02-10 07:04:57 [7] [ERROR] Error handling request
2014-02-10T07:04:57.483414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-02-10T07:04:57.482250+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com request_id=d738b054-2071-4c0c-a790-c64430930277 fwd="67.105.106.9" dyno=web.1 connect=1ms service=867ms status=500 bytes=135
2014-02-10T07:04:57.483414+00:00 app[web.1]: Traceback (most recent call last):
2014-02-10T07:04:57.483414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2014-02-10T07:04:57.483414+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2014-02-10T07:04:57.483414+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:04:57.483414+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2014-02-10T07:04:57.483414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2014-02-10T07:04:57.483414+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-02-10T07:04:57.483652+00:00 app[web.1]:     response = self.full_dispatch_request()
2014-02-10T07:04:57.483414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2014-02-10T07:04:57.483652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2014-02-10T07:04:57.483652+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:04:57.483652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2014-02-10T07:04:57.483652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2014-02-10T07:04:57.483652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2014-02-10T07:04:57.483652+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2014-02-10T07:04:57.483652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2014-02-10T07:04:57.483652+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2014-02-10T07:04:57.483652+00:00 app[web.1]:     rv = self.dispatch_request()
2014-02-10T07:04:57.483823+00:00 app[web.1]:   File "/app/rosterrun.py", line 309, in show_entries
2014-02-10T07:04:57.483823+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
2014-02-10T07:04:57.483823+00:00 app[web.1]:     context, ctx.app)
2014-02-10T07:04:57.483823+00:00 app[web.1]:     rv = template.render(context)
2014-02-10T07:04:57.483823+00:00 app[web.1]:     return render_template('show_entries.html', combinations=availableParties, characters=chars)
2014-02-10T07:04:57.483823+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
2014-02-10T07:04:57.483823+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
2014-02-10T07:04:57.483823+00:00 app[web.1]:     return self.environment.handle_exception(exc_info, True)
2014-02-10T07:04:57.484340+00:00 app[web.1]:     <td><a href="{{ url_for('market_results') }}">Market Results</a></td>
2014-02-10T07:04:57.484340+00:00 app[web.1]:     {% extends "layout.html" %}
2014-02-10T07:04:57.484340+00:00 app[web.1]:     {% block body %}{% endblock %}
2014-02-10T07:04:57.484340+00:00 app[web.1]:   File "/app/templates/layout.html", line 16, in top-level template code
2014-02-10T07:04:57.484340+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
2014-02-10T07:04:57.484340+00:00 app[web.1]:     return appctx.app.handle_url_build_error(error, endpoint, values)
2014-02-10T07:04:57.483823+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
2014-02-10T07:04:57.484340+00:00 app[web.1]:   File "/app/templates/show_entries.html", line 9, in block "body"
2014-02-10T07:04:57.484340+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:04:57.484340+00:00 app[web.1]:   File "/app/templates/show_entries.html", line 1, in top-level template code
2014-02-10T07:04:57.483823+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:04:57.484517+00:00 app[web.1]:     raise BuildError(endpoint, values, method)
2014-02-10T07:04:57.484340+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
2014-02-10T07:04:57.484517+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
2014-02-10T07:04:57.484517+00:00 app[web.1]:     force_external=external)
2014-02-10T07:04:57.484517+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
2014-02-10T07:04:57.484517+00:00 app[web.1]: BuildError: ('market_results', {}, None)
