2014-02-10T07:52:49.315601+00:00 app[web.1]: show entries
2014-02-10T07:52:49.315601+00:00 app[web.1]: already have ids in session  None None
2014-02-10T07:52:49.320992+00:00 app[web.1]: get all combinations
2014-02-10T07:52:49.323366+00:00 app[web.1]: 2014-02-10 07:52:49 [7] [ERROR] Error handling request
2014-02-10T07:52:49.323366+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2014-02-10T07:52:49.323366+00:00 app[web.1]: Traceback (most recent call last):
2014-02-10T07:52:49.323366+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-02-10T07:52:49.323366+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-02-10T07:52:49.323366+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2014-02-10T07:52:49.323610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2014-02-10T07:52:49.323366+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2014-02-10T07:52:49.323610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2014-02-10T07:52:49.323610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2014-02-10T07:52:49.323610+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:52:49.323610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2014-02-10T07:52:49.323366+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2014-02-10T07:52:49.323366+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2014-02-10T07:52:49.323610+00:00 app[web.1]:     response = self.full_dispatch_request()
2014-02-10T07:52:49.323876+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2368, in _execute_and_instances
2014-02-10T07:52:49.323610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2014-02-10T07:52:49.323610+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2014-02-10T07:52:49.323610+00:00 app[web.1]:     rv = self.dispatch_request()
2014-02-10T07:52:49.323876+00:00 app[web.1]:     cur = PartyCombo.query.all()
2014-02-10T07:52:49.323876+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2241, in all
2014-02-10T07:52:49.323610+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2014-02-10T07:52:49.323876+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2353, in __iter__
2014-02-10T07:52:49.323366+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:52:49.323876+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
2014-02-10T07:52:49.324484+00:00 app[web.1]:     compiled_sql, distilled_params
2014-02-10T07:52:49.324484+00:00 app[web.1]:     exc_info
2014-02-10T07:52:49.324659+00:00 app[web.1]:     cursor.execute(statement, parameters)
2014-02-10T07:52:49.324659+00:00 app[web.1]: InternalError: (InternalError) current transaction is aborted, commands ignored until end of transaction block
2014-02-10T07:52:49.323876+00:00 app[web.1]:     return list(self)
2014-02-10T07:52:49.323876+00:00 app[web.1]:     params)
2014-02-10T07:52:49.324484+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
2014-02-10T07:52:49.323876+00:00 app[web.1]:     return self._execute_and_instances(context)
2014-02-10T07:52:49.324484+00:00 app[web.1]:     context)
2014-02-10T07:52:49.323876+00:00 app[web.1]:   File "/app/rosterrun.py", line 301, in show_entries
2014-02-10T07:52:49.324484+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb)
2014-02-10T07:52:49.323876+00:00 app[web.1]:     result = conn.execute(querycontext.statement, self._params)
2014-02-10T07:52:49.324484+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
2014-02-10T07:52:49.324484+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
2014-02-10T07:52:49.324484+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
2014-02-10T07:52:49.324484+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
2014-02-10T07:52:49.324659+00:00 app[web.1]:  'SELECT party_combo.id AS party_combo_id, party_combo.g_spreadsheet_id AS party_combo_g_spreadsheet_id, party_combo.g_worksheet_id AS party_combo_g_worksheet_id, party_combo."partyIndex" AS "party_combo_partyIndex", party_combo."instanceName" AS "party_combo_instanceName", party_combo."playerName" AS "party_combo_playerName", party_combo.name AS party_combo_name, party_combo."className" AS "party_combo_className", party_combo.rolename AS party_combo_rolename \nFROM party_combo' {}
2014-02-10T07:52:49.324484+00:00 app[web.1]:     context)
2014-02-10T07:52:49.324659+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
2014-02-10T07:52:49.324607+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com request_id=d730c279-e686-45fd-a477-a2b40e617c9c fwd="67.105.106.9" dyno=web.1 connect=1ms service=12ms status=500 bytes=135
2014-02-10T07:53:05.085586+00:00 heroku[api]: Starting process with command `python` by andygee@gmail.com
2014-02-10T07:53:19.033744+00:00 heroku[run.4104]: Awaiting client
2014-02-10T07:53:19.085003+00:00 heroku[run.4104]: Starting process with command `python`
2014-02-10T07:53:19.007709+00:00 heroku[run.4104]: State changed from starting to up
2014-02-10T07:53:38.505404+00:00 heroku[run.4104]: State changed from up to complete
2014-02-10T07:53:38.481502+00:00 heroku[run.4104]: Process exited with status 0
2014-02-10T07:53:44.325630+00:00 app[web.1]: show entries
2014-02-10T07:53:44.325630+00:00 app[web.1]: cannot find gdoc name
2014-02-10T07:53:44.325199+00:00 app[web.1]: No job in session
2014-02-10T07:53:44.325696+00:00 app[web.1]: already have ids in session  None None
2014-02-10T07:53:44.346038+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-02-10T07:53:44.346038+00:00 app[web.1]: get all combinations
2014-02-10T07:54:01.959305+00:00 app[web.1]: cannot bind action
2014-02-10T07:54:04.308572+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2014-02-10T07:54:04.272537+00:00 app[web.1]: cannot bind action
2014-02-10T07:54:04.308572+00:00 app[web.1]: 2014-02-10 07:54:04 [7] [ERROR] Error handling request
2014-02-10T07:54:04.308572+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-02-10T07:54:04.308572+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2014-02-10T07:54:04.308572+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2014-02-10T07:54:04.308572+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2014-02-10T07:54:04.308572+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:54:04.308917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2014-02-10T07:54:04.308917+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:54:04.308917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2014-02-10T07:54:04.308572+00:00 app[web.1]: Traceback (most recent call last):
2014-02-10T07:54:04.308572+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-02-10T07:54:04.308572+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2014-02-10T07:54:04.309151+00:00 app[web.1]:     return render_template('treasury.html', treasures=t)
2014-02-10T07:54:04.308917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2014-02-10T07:54:04.308917+00:00 app[web.1]:     rv = self.dispatch_request()
2014-02-10T07:54:04.308917+00:00 app[web.1]:     response = self.full_dispatch_request()
2014-02-10T07:54:04.308917+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2014-02-10T07:54:04.308917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2014-02-10T07:54:04.308917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2014-02-10T07:54:04.308917+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2014-02-10T07:54:04.309151+00:00 app[web.1]:   File "/app/rosterrun.py", line 347, in treasury
2014-02-10T07:54:04.309151+00:00 app[web.1]:     return self.get_template(template_name_or_list, parent, globals)
2014-02-10T07:54:04.309151+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
2014-02-10T07:54:04.309151+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
2014-02-10T07:54:04.309151+00:00 app[web.1]:     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
2014-02-10T07:54:04.309151+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
2014-02-10T07:54:04.309151+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
2014-02-10T07:54:04.309151+00:00 app[web.1]:     template = self.loader.load(self, name, globals)
2014-02-10T07:54:04.309151+00:00 app[web.1]:     return self._load_template(name, self.make_globals(globals))
2014-02-10T07:54:04.309923+00:00 app[web.1]:     self.handle_exception(exc_info, source_hint=source)
2014-02-10T07:54:04.309923+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
2014-02-10T07:54:04.309923+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-02-10T07:54:04.309923+00:00 app[web.1]: TemplateAssertionError: no test named 'None'
2014-02-10T07:54:04.309923+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
2014-02-10T07:54:04.309923+00:00 app[web.1]:     code = environment.compile(source, name, filename)
2014-02-10T07:54:04.309923+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
2014-02-10T07:54:04.309923+00:00 app[web.1]:   File "/app/templates/treasury.html", line 42, in template
2014-02-10T07:54:04.309923+00:00 app[web.1]:     <!--<td>{% if t.guildtransaction_id is None %}<input type=submit name=buy value=Buy>{% else %}{{ t.guildtransaction_id|safe }}  {% endif %}</>-->
2014-02-10T07:53:44.443749+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com request_id=a0794865-00d2-42b8-99ae-9933a021a716 fwd="67.105.106.9" dyno=web.1 connect=0ms service=128ms status=200 bytes=4925
Terminate batch job (Y/N)? 
